// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avkhtkehlwhslxzyyfqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2a2h0a2VobHdoc2x4enl5ZnFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc0MzgzNTcsImV4cCI6MjA1MzAxNDM1N30.SjUPJKmQk5vwkPk7KQLnxW2OMyPoX7we7P5rZlzbNpA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);